### ISSUE TITLE
Getting this to work with the latest mycroft unstable

### ISSUE THREAD

**Issue by groupwhere** [btotharye/mycroft-homeassistant#24]
I don't have a patch, per se.  But, I could create one.  Basically, in __init__.pym replace "settings" with "config", then remove calls to the strTobool function.

**Comment by nielstron** [comment]
Are you sure that this would work with config instead of settings? It seems like the settings object resembles the data given at home.mycroft.ai, on which this skill should rely.
Calls to strToBool function can be replaced with "== 'true'" since checkboxes are allowed at home.mycroft.ai. See #25 where this is implemented

**Comment by groupwhere** [comment]
Sorry, but I am now back on the stable release version and cannot test this.  But, I believe this was what I did to get it working.

**Comment by btotharye** [comment]
sorry I've been crazy busy at work I'm going to work on setting this back up this weekend.

**Comment by XxCRSxX** [comment]
@btotharye Can't wait! 👍 :)

**Comment by btotharye** [comment]
still working on this, skill appears to be broken for the 18b version atm.

**Comment by btotharye** [comment]
This should now work with 18.2.6 beta I just confirmed it on my home setup.

**Comment by btotharye** [comment]
this should be resolved now @groupwhere let me know if it isn't, I have it setup now to install the skill but not try to load the connection until the host part is at least filled out.
