### ISSUE TITLE
Homeassistant 0.77.2 - Access to home assistant server fails...

### ISSUE THREAD

**Issue by andlo** [btotharye/mycroft-homeassistant#62]
Aftter updating to homeassistant 0.77.2 remember to enambel legacy_api auhentification mycroft wont access homeassistant :( 

 turn off bathroom
 >> Access to home assistant server at http://xxxxxxx.duckdns.org:8123/api/states failed. 

The strange part here is that the urs is http and not https which is configured in skill setting, and homeassistant is configured to accept connection whith ssl and on port 8123

Well I did update homeassistant AND mycroft so mycroft is also running 18.08...

by the way - I looove mycroft and homeassustant and this mycroft-homeassistant skil is the best ever ;)

**Comment by cooljimy84** [comment]
Got this as well. Pulled front GitHub a few hours ago.

Same thing, tho I thought it was an issue with my config as it says in the logs and speaks http:// rather than Https.
I've tried unticking and reticking, didn't help. I also tried adding Https:// to the server address, I just get an error about invalid data.
